# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alex's web log
email: alex.shinkevich@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sometimes your thought and experience you have faced with may be interesting and even useful for other people.
  In this blog I would like to share some important for me events from my everyday experience with the World.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alexshin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  alexshin
linkedin_username: ashinkevich
facebook_username: alex.shinkevich

timezone: Europe/Minsk

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - emoji_for_jekyll
show_excerpts: true
rss: rss feed
header_pages:
  - about.md
  - links.md

disqus:
    shortname: alexshin

google_analytics: UA-123055233-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
